apiVersion: v1
kind: Service
metadata:
  name: email-site-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: email
    type: front-end
