apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    name: email-sender
    instance: email-service
    type: back-end
spec:
  type: ClusterIP
  ports:
    - name: web
      targetPort: 8080
      port: 80
  selector:
    app: email
    type: back-end
