apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  labels:
    app: email
    tier: back-end
spec:
  selector:
    matchLabels:
      app: email
  replicas: 3
  template:
    metadata:
      labels: 
        app: email
        type: back-end
    spec:
      containers:
        - name: email-service
          image: leonardorothier/email-service:v3
          ports:
            - containerPort: 8080
          env:
            - name: SENDER_COMPRAS_USER
              valueFrom:
                secretKeyRef:
                  name: gmail-compras-credentials
                  key: username
            - name: SENDER_COMPRAS_PASS
              valueFrom:
                secretKeyRef:
                  name: gmail-compras-credentials
                  key: password
            - name: SENDER_FINANCEIRO_USER
              valueFrom:
                secretKeyRef:
                  name: gmail-financeiro-credentials
                  key: username
            - name: SENDER_FINANCEIRO_PASS
              valueFrom:
                secretKeyRef:
                  name: gmail-financeiro-credentials
                  key: password
            - name: SENDER_CONTROLE_USER
              valueFrom:
                secretKeyRef:
                  name: gmail-controle-credentials
                  key: username
            - name: SENDER_CONTROLE_PASS
              valueFrom:
                secretKeyRef:
                  name: gmail-controle-credentials
                  key: password
      restartPolicy: Always
