apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  labels:
    app: email
    tier: back-end
spec:
  selector:
    matchLabels:
      app: email
  replicas: 3
  template:
    metadata:
      labels: 
        app: email
        type: back-end
    spec:
      containers:
        - name: email-service
          image: leonardorothier/email-service:v5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SENDER_PROVIDER
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: sender-provider
            - name: SENDER_NAMES
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: sender-names
            - name: SERVICE_ACCOUNT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: service-account-email
            - name: SERVICE_ACCOUNT_PASS
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: service-account-pass
            - name: SENDER_COMPRAS_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: sender-compras-email
            - name: SENDER_FINANCEIRO_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: sender-financeiro-email
            - name: SENDER_CONTROLE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: email-credentials
                  key: sender-controle-email
      restartPolicy: Always
